### ISSUE TITLE
Devise missing translation

### ISSUE THREAD

**Issue by LeBIGest** [recipyhq/recipy#108]
Ajout des traductions manquantes dans les différentes vues de devise

**Comment by guillaumecauchois** [comment]
Ne fonctionne toujours pas...
Dans l'api PUT /users avec un mauvais mot de passe me retourne : 
"translation missing: fr.activerecord.error.models.user.attributes...."

**Comment by guillaumecauchois** [comment]
Apparemment corrigé d'après Robin
