### ISSUE TITLE
Api | user sign_up

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#125]
Quand j'appel la route de sign-up  [https://staging-recipy.herokuapp.com/fr/api/users] je reçois une erreur 500 et un retour d'erreur en HTML m'en informant.
Je suis bien dans le mailtrap mais je ne reçois jamais l'email d'inscription (certainement dû à l'erreur 500)  alors que mon compte est correctement créé en base car quand j'essaie de me réinscrire j'ai le retour suivant :

```
{
    "status": "error",
    "data": {
        "id": null,
        "provider": "email",
        "uid": "",
        "allow_password_change": false,
        "email": "testb@testa.fr",
        "created_at": null,
        "updated_at": null
    },
    "errors": {
        "email": [
            "Un compte existe déjà avec cette adresse mail. Veuillez réessayer"
        ],
        "full_messages": [
            "Courriel Un compte existe déjà avec cette adresse mail. Veuillez réessayer"
        ]
    }
}
```

De ce problème je ne peux donc pas appelé la route de sign_in étant donné que ne suis pas en mesure d'activer mon compte. Je reçois le retour suivant :
```
{
    "success": false,
    "errors": [
        "Un e-mail de confirmation de votre compte a été envoyé à 'testb@testa.fr'. Merci de suivre les instructions afin de valider votre compte"
    ]
}
```

J'ai testé tout fonctionne en ne passant pas par l'api mais en passant directement par le front et donc comme le disais @ventinc#0671  ça semble fonctionner pour vous mais pas pour l'utilisation que j'en ai (je reçois bien l'email de confirmation, etc...).

Quelqu'un serait chaud du coup pour corriger se problème ? (étant donné que ça ne vient pas d'un problème de merge comme on le pensait)

**Comment by beauraF** [comment]
J'ai joué un peu avec postman et aucun soucis de mon coté.
