### ISSUE TITLE
FIx simple form messages

### ISSUE THREAD

**Issue by LeBIGest** [recipyhq/recipy#127]
Issue to fix simple form front errors :+1: 
- Bad placing of errors messages
- Missing translations

**Comment by beauraF** [comment]
Les missings translation, c'est pas normal. Faut regarder du coté de `Devise-i18n`.

**Comment by guillaumecauchois** [comment]
@LeBIGest Je te laisse corriger le problème.
@beauraF tu te chargeras de valider la PR ;)
