### ISSUE TITLE
Devise | OAuth | Persistance

### ISSUE THREAD

**Issue by Panzershrekk** [recipyhq/recipy#128]
J'ai l'impression que, lorsque je me connecte avec facebook ou autre, je ne suis pas considéré comme étant "Connecté" sur Recipy. je suppose qu'il faut faire quelque chose avec oauth mais je vois pas quoi ?

**Comment by Panzershrekk** [comment]
@beauraF Je sais pas si t'as une idée ?

**Comment by beauraF** [comment]
Je vais m'occuper de faire une grosse passe sur tout Devise et corriger tous les soucis. Vous inquiétez plus de ces sujets.

**Comment by Panzershrekk** [comment]
Ok merci =)

**Comment by beauraF** [comment]
C'est corrigé pour API. Par contre, j'ai pas pu fix pour tiwtter, les credentials sont pas bon. Me faut vos logs.
