### ISSUE TITLE
Utilisateurs | Ajouter une photo de profil au comptes utilisateurs

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#130]
Ajout d’une photo de profil au compte utilisateur
- [ ] Formulaire d’upload d’une photo de profil

**Comment by LeBIGest** [comment]
@beauraF t'as une idée de lib pour ça ?
j'ai trouvé :
-  paperclip (http://www.peoplecancode.com/tutorials/users-avatars-uploading-images-using-paperclip)
- carrierWave (https://code.tutsplus.com/tutorials/rails-image-upload-using-carrierwave-and-devise--cms-25681)

**Comment by beauraF** [comment]
Tu as cité les deux libs les plus connu. Mais depuis rails 5.2 nous avons : https://guides.rubyonrails.org/active_storage_overview.html

**Comment by guillaumecauchois** [comment]
+ Spécifier dans le documentation de l'api sur les routes d'édition du profil

Comme discuté ensemble on va certainement faire un système comme suit :
 - Je créé mon compte je suis automatiquement en cuisinier
 - Si je le souhaite je passe en un clic à une solution "Je suis producteur" qui me permet de rajouter des fonctionnalités à mon environnement sur le site internet (Ajouter des produits que je propose en tant que producteur)
