### ISSUE TITLE
Ingrédients | Création de l'entité ingrédient

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#133]
Le but est de pouvoir manipuler des entités de type ingrédient
- [x] Une table et un modèle permettant de définir la notion d’ingrédient

**Comment by beauraF** [comment]
Crée la PR et ping moi dessus. C'est plus simple. Oublie pas de la link avec l'issue.
Mais pour te répondre sans snippet de code, il suffit de déclarer la ressource dans chaque namespace où tu veux qu'il soit. :)

**Comment by guillaumecauchois** [comment]
Voir pour ajouter **une photo** de l'ingrédient dans le modèle ainsi qu'une notion de ### liste de tag en mode "Fruit", "Janvier", "Février", "Mars"

**Comment by guillaumecauchois** [comment]
Il faut revoir entièrement l’architecture des entités ingrédients et recettes. S'il vous plait @LeBIGest et @Arthaox pouvez-vous travailler tous ensemble pour réussir à rendre une architecture au top est bien pensée, dans la version actuel ça manque cruellement d'une vrai architecture. Est-ce qu'on peut se fixer un objectif que pour le 22/01 vous aillez un UML complet sur la notion d'ingrédients, recette et tout ce qui en découle du style quantité ?
Pour le coup cette tâche à du être fait un peu tête baissé alors qu'il aurait fallut un peu plus de réflexion en amont.

Ensuite on verra pour le développement.

**Comment by guillaumecauchois** [comment]
Axes d’amélioration de votre architecture pour les ingrédients :
- Ajouter une NOUVELLE classe pour les quantités d'ingrédients par une simple string ça n'est juste pas utilisable et ça ne respect tout simplement même pas les principe de développement objet / rails.
- Il faudrait imaginer que pour chaque ingrédient qu'on va créer, on sera capable de donner une correspondance "en gramme", "en cuillère à café", "en cuillère à coupe", "en pincé" ... etc. Je veux être capable de pouvoir faire des correspondance par rapport à n'importe qu'elle configuration de quantité qui aura été intégré à l'intérieur même de l'ingrédient.
Exemple : 1 c. à café de sucre = 15g / 1c. à soupe de sucre = 30g / 1 pincé de sucre = 3g / etc en fonction du nombre de configuration qu'on aura enregistrer en son sein. Et ainsi ça reste "User friendly" et utilisable, manipulable.
- Je ne sais pas si c'est fait, mais intégrer une image dans les ingrédients
- Un titre une description
- .... Je vous laisse réfléchir si y'a d'autre choses à voir.

Attention, bien développer le model de façon rails compliant avec des has_many etc... Pas toujours été le cas avant d'après le feedback d'autre personne.
