### ISSUE TITLE
User | Email confirmation d'inscription

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#158]
Lorsque je créé un nouvel utilisateurs (depuis l'api en tout cas mais peut-être le problème sur la webapp) je reçois bien un email de confirmation de création de compte mais celui-ci est vide (uniquement une entête).
Je ne peux donc pas faire valider mon compte.

**Comment by Ventinc** [comment]
J'ai pas encore d'idée je regarde ça pour le corriger si possible avant la réu demain
