### ISSUE TITLE
Home | Création d'une maquette de la page d’accueil

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#168]
- [ ] Création d'une maquette pour imaginer une interface de ce à quoi devrait ressembler la page d'accueil de notre site web (Inspiration : Marmiton). Ne pensez que en terme de design, un truc sexy et agréable
- [ ] Intégrer directement la recherche de recette
- [ ] Pas d'image dégelasse
- [ ] Peut-être intégrer un bloc "Les dernières recettes" / "Les recettes les mieux notés"

**Comment by PierreCooper** [comment]
C'est noté chef

**Comment by guillaumecauchois** [comment]
Maquette reçu sur Discord. En attente du retour de toute la team.

**Comment by guillaumecauchois** [comment]
Semble validé par l'équipe dans l'ensemble. A prendre en compte : 
 - Certainement ajouter un blur sur le fond d'écran pour que ça donne un peu de profondeur et que ça évite de faire un peu fouillis par la suite
 - Si tu peux essayer de mettre bien en pleine largeur d'écran le bloc avec les recettes
 - Certainement épurer un peu plus les informations affichées dans le bloc d'information d'une recette (supprimer de ce bloc pour cette page la notion de difficulté de recette
 - Un truc que je rajouterai peut-être c'est de bien faire en sorte que le background soit de bonne qualité et en même temps pas trop lourd en poids pour éviter de ralentir le chargement de la page

**Comment by guillaumecauchois** [comment]
![maquette_1_page_accueil_recipy](https://user-images.githubusercontent.com/15093128/51686284-66decb80-1ff0-11e9-8f5a-255142d4e778.png)
