### ISSUE TITLE
Cooker | Carnets de recettes

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#181]
Création de carnets de recettes sous formats d’albums pour sauvegarder ses recettes préférés, faire des carnets par thèmes, etc…
- [x] Création de la notion de carnet de recettes
- [x] Ajout de l’entité à l’UML
- [x] Page de création d'un carnet de recette (avec un nom et une liste de recette associée)
- [x] Page de visualisation de la liste de « mes carnets de recettes »
- [x] Page de visualisation d’un carnet de recettes
- [x] Ajout rapide d’une recette à un carnet directement sur la fiche recette (possibilité de créer des carnets sur la page à la volée, facilement)
- [x] Développement des routes api et documentation dans Postman

**Comment by guillaumecauchois** [comment]
@Thornolf peux-tu me faire un point de ton avancement stp ? ;)

**Comment by Thornolf** [comment]
API rdy & Web aussi, désolé j'ai pas vu ton poke c'est vraiment bizarre github qui envoie pas les mails au bon moment.

**Comment by Thornolf** [comment]
Je close, tout à était fait pour le sprint antérieur.

**Comment by guillaumecauchois** [comment]
Good
