### ISSUE TITLE
Producer | Fiche producteur

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#187]
Donner de la visibilité aux producteurs en leur permettant d’avoir une fiche visible par tous les cuisiniers
 - [ ] Visuel basé sur la fiche profil d’un utilisateur
 - [ ] Affichage des informations de bases du producteur
 - [ ] Liste des points de collectes (Nom, adresses, horaires …)
 - [ ] Les produits proposés par les points de collectes

**Comment by guillaumecauchois** [comment]
Récapitulatif du rendez-vous Web#Producer : 
- Julien attribué à cette tâche
- Pour le prochain rendez-vous dans deux semaines : Faire une maquette visuelle de ce à quoi devrait ressembler le page de profil d'un producteur à travailler en collaboration avec la personne sur le ticket #182

**Comment by guillaumecauchois** [comment]
Exemple de ce qui est réalisé sur mobile : 
![image](https://user-images.githubusercontent.com/15093128/57197348-8b8afd80-6f66-11e9-8575-32ebe828c480.png)

**Comment by guillaumecauchois** [comment]
Essayer de faire le maximum (au moins niveau front) pour rendre quelque chose de similaire à la vue mobile ci-dessus

**Comment by guillaumecauchois** [comment]
@MoonPandragon , est-ce que tu peux me présenter ton avancement ce Jeudi est qu'on réfléchisse ensemble à ce qui est prioritaire pour ce ticket ?

**Comment by Thornolf** [comment]
Ca a avancé ?

**Comment by guillaumecauchois** [comment]
@MoonPandragon

**Comment by guillaumecauchois** [comment]
Base terminée, Robin est sur l'amélioration de celle-ci
