### ISSUE TITLE
Producer | Réservation de produits

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#190]
- [ ] Permettre de réserver des produits directement sur la page de visualisation des produits proposés par un producteur
- [ ] Pouvoir décider de réserver une certaine quantité de produit dans un espace dédié de la fiche d’un point de collecte
- [ ] La liste des réservations de produits doit être visible dans un espace de « mon compte » en tant que cuisinier
- [ ] La liste des réservations de produits d’un point de collecte doit être visible dans le « panel producteur »
- [ ] Le producteur doit pouvoir programmer par point de collecte s’il souhaite valider manuellement ou automatiquement les réservations des cuisiniers
- [ ] Le producteur doit recevoir une notification pour l’arrivée d’une nouvelle réservation
- [ ] Le cuisinier doit recevoir une notification si la réservation est acceptée ou refusée
- [ ] Le cuisinier doit pouvoir annuler une réservation de produit dans l’unique cas où la demande de validation est en cours de la part du producteur
- [ ] Dans le cas d’une annulation, le producteur et le cuisinier reçoivent une notification leur confirmation l’annulation.
- [ ] Développement des routes api et documentation dans Postman

**Comment by guillaumecauchois** [comment]
Plus d'actualité pour le moment.
Dans un premier temps on va se concentrer sur mettre au centre des recettes, liste de course les producteurs, et permettre un moyen de contact direct simple.
A conserver pour la suite.

**Comment by guillaumecauchois** [comment]
Apparemment, @MoonPandragon tu es partis là-dessus, pas de soucis.
Je t'assigne le ticket, à toi de voir ce que tu peux faire pour avancer un maximum.
Piste de réflexion pour rendre quelque chose :
- Pas de gestions des stocks

**Comment by guillaumecauchois** [comment]
Objectif : 
 - Pouvoir réserver des produits / quantité
 - Générer une sorte de "liste de réservation" et l'envoyer par mail au producteur avec les informations de contacts.
--> Permettre la création d'un nouveau canal de vente simple

**Comment by Thornolf** [comment]
On freeze la prod ce soir.

**Comment by Thornolf** [comment]
Je close ça, on verra pour plus tard.
