### ISSUE TITLE
Assistant Vocal | Alexa

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#192]
Préparation au développement d’un skill pour l’assistant Amazon Alexa
 - [ ] Recherche sur l’intégration d’un assistant vocal Amazon Alexa
 - [ ] Pouvoir demander à Alexa "Que manger ce midi ?"

**Comment by Thornolf** [comment]
Ce n'est plus pertinent pour l'instant, à revoir pour plus tard.
