### ISSUE TITLE
Assitant Vocal | Google Assistant

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#193]
Préparation au développement d’un skill pour l’assistant Google « Google Assistant »
 - [ ] Recherche sur l’intégration d’un assistant vocal Google Assistant
 - [ ] Pouvoir demander à Google Assistant "Que manger ce midi ?"

**Comment by Thornolf** [comment]
Ce n'est plus pertinent pour l'instant, à revoir pour plus tard.
