### ISSUE TITLE
Initialisation de la base des ingrédients / recettes

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#197]
- [x] Rédaction d'environ 40 recettes correctement formatés, rattachés à des ingrédients

**Comment by guillaumecauchois** [comment]
Nous sommes en environ une quinzaine de recette crées, il en faudrait 40 pour la mise en place de la BETA.

**Comment by guillaumecauchois** [comment]
25 recettes ont été créées sur le projet. Il en faudrait quasiment le double.

**Comment by Thornolf** [comment]
Nous possédons maintenant un grand nombre de recettes. Je close.
