### ISSUE TITLE
User | Intégration d'un prénom

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#204]
Pour personnaliser l'expérience utilisateur, il faut intégrer à la notion d'utilisateur un prénom
- [ ] Ajouter le prénom
- [ ] Mettre à jour l'api
- [ ] Mettre à jour postman

**Comment by guillaumecauchois** [comment]
Fais par @MoonPandragon

**Comment by guillaumecauchois** [comment]
Pas de nouvelle de cette issue ?

**Comment by MoonPandragon** [comment]
Hello, 

On avait décidé de récupérer le nom et prénom lorsque l'utilisateur devenait producer et pas a l'inscriptions, de mon point de vue c’était une feature web uniquement donc j'ai pas fais d'api pour ça

**Comment by guillaumecauchois** [comment]
Semble terminé, à vérifié après intégration dans le postman.
