### ISSUE TITLE
User | API | get user informations

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#205]
Pour la réalisation du ticket de page utilisateur et producteur sur le mobile j'ai besoin d'une route de récupération d'informations utilisateur comprenant: 
id, prénom, photo de profil

Qui me permettra d'afficher les informations de base de l'utilisateur.

A faire au plus vite possible, en fonction du temps que vous avez.

**Comment by guillaumecauchois** [comment]
@recipyhq/web qui peut faire ça pour moi ?

**Comment by Ventinc** [comment]
Fais dans la précédente version {{API_URL}}/user/info?user_id=1 mais à améliorer pour plus tard faire une meilleure route

**Comment by guillaumecauchois** [comment]
OK done.
