### ISSUE TITLE
Correction de l'authentification

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#221]
- [ ] Lors de l'inscription après validation du formulaire je suis renvoyé vers la landing page et sans message de succès.
- [ ] Lors de la validation de mon clic (après clic sur le lien dans l'email de validation du compte) je suis simplement renvoyé vers le login sans message d'erreur ou de succès.

**Comment by MoonPandragon** [comment]
Vincent, a fais tout les messages via la pop-up
Pour les redir c'était fait, ca a était retirer lorsqu'on a tout merge, je vais le remettre ca va aller vite

**Comment by guillaumecauchois** [comment]
Comme vu ensemble, on passe ce petit problème de redirection à Vincent.
