### ISSUE TITLE
Page de recette - Double affichage de l'entête

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#222]
Vu sur le stagging, l'affichage de l'entête de la recette est en double ?
![image](https://user-images.githubusercontent.com/15093128/57110785-0fac6d80-6d3a-11e9-9551-0b6882c39140.png)

**Comment by Thornolf** [comment]
@Ventinc l'a fix normalement, c'est juste lors de mon merge. C'est tout bête mais Vincent l'avait fix peut être que la pullrequest n'a pas été accepté ?

**Comment by guillaumecauchois** [comment]
Peut être je sais pas trop je viens juste de voir ça sur stagging ???

Le 3 mai 2019 00:29, Thornolf <notifications@github.com> a écrit :

@Ventinc<https://github.com/Ventinc> l'a fix normalement, c'est juste lors de mon merge. C'est tout bête mais Vincent l'avait fix peut être que la pullrequest n'a pas été accepté ?

**Comment by Thornolf** [comment]
Toujours là ? Normalement Vincent est repassé sur les design il a du traiter l'erreur ?

**Comment by Thornolf** [comment]
C'est fix dans le nouveau design, tu peux close l'issue @guillaumecauchois

**Comment by guillaumecauchois** [comment]
Vu c'est good, thx
