### ISSUE TITLE
Installer le serveur de production

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#223]
J'ai lancé le promote to production pour mettre en production l'environnement de stagging, seulement il semble y avoir un problème. A regarder (log donne une erreur sql sur les prospects)

**Comment by guillaumecauchois** [comment]
@recipyhq/web qui est dispo pour s'occuper de cette issue ?

**Comment by Thornolf** [comment]
Recipy est accessible sur Recipy.fr
