### ISSUE TITLE
Newsletter empêche l'inscription

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#233]
le bolean newsletter empêche l'inscription sur staging, pourquoi ? On a eu le soucis avec Robin hier. Ca fonctionne en local par contre.

**Comment by Thornolf** [comment]
Le soucis a été résolut ?

**Comment by MoonPandragon** [comment]
Désolé j'ai pas trop eu le temps de m'en occuper, ca fonctionne en local mais pas en staging?

**Comment by Thornolf** [comment]
Oui c'est ça, on l'a juste commenté normalement.

**Comment by guillaumecauchois** [comment]
@MoonPandragon : A voir le log sur stagging pour avoir des informations sur l'erreur.
N'hésite pas à tagger @recipyhq/web sur discord pour avoir plus d'aide et peut-être trouver quelqu'un qui pourra t'orienter face à l'erreur rencontrée.

**Comment by MoonPandragon** [comment]
Corriger sur la PR #262, je ferme l'issue
