### ISSUE TITLE
Problème d'UX sur création de recette

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#235]
Si un element est mauvais, toutes les entrés sont supprimé (Imaginons genre on a juste oublié de mettre le temps de cuisson, toute notre description, étapes, ingrédients etc. est remit à 0)

Ce n'est pas prio mais bon c'est un peu frustrant pour l'expérience utilisateur

**Comment by guillaumecauchois** [comment]
https://stackoverflow.com/questions/40847923/how-does-rails-keep-the-form-data-when-validations-fail

Comme vu ensemble voir pour utiliser ce helper en donnant le params en paramètre :)

**Comment by guillaumecauchois** [comment]
@PierreCooper nouveau assigné

**Comment by Thornolf** [comment]
On a essayé de le fix mais impossible, faudrait retravaillé entièrement le model. Je close.
