### ISSUE TITLE
Recipe | Description Ingrédient

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#236]
Est-ce bien pertinent d'obliger une description d'un ingrédient ? Par exemple je me suis retrouvé à créer des ingrédients comme l'eau ou le sucre. Est-ce bien intéressant de les décrires ?

**Comment by guillaumecauchois** [comment]
Je me posais la même question la dernière fois, effectivement dans une prochaine version il faudra prévoir la possibilité d'une description nullable

**Comment by guillaumecauchois** [comment]
A mettre en place asap
