### ISSUE TITLE
Broken link des Image enregistré en staging 

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#237]
A chaque fois qu'une recette ou un notebook ou quoi que ce soit qui nécessite une image est créer après quelques temps (1h ou autre) l'element se retrouve en broken link. Ca me semble bizarre car il est bien ajouté via le processus classique d'ajout d'image sur Rails. Est-ce que ça viendra d'un soucis d'Heroku ?

**Comment by LeBIGest** [comment]
https://devcenter.heroku.com/articles/active-storage-on-heroku
lien du pourquoi du comment :disappointed:

**Comment by guillaumecauchois** [comment]
@LeBIGest existe-il une solution ?

**Comment by Thornolf** [comment]
Faudrait qu'on ai un hebergeur genre AWS je penses pour les images si j'avais bien compris l'histoire. P'tet un truc gratos ou moins cher ? Quid d'aller taper directement sur des URL pour les images de déco ? C'est pas dingue mais ça pourrait alléger et pas besoin de payer quelque chose comme ça

**Comment by Thornolf** [comment]
Ou y aurait pas un moyen de l'heberger sur un dédié ?

**Comment by LeBIGest** [comment]
https://medium.com/@pjbelo/setting-up-rails-5-2-active-storage-using-google-cloud-storage-and-heroku-23df91e830f8

**Comment by guillaumecauchois** [comment]
Ah voir pour l'utilisation d'une solution chez Microsoft AZURE (https://portal.azure.com/) : "Blob storage container"
à voir assez vite

**Comment by LeBIGest** [comment]
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-ruby

**Comment by Thornolf** [comment]
Robin l'a fix en utilisant Google Cloud Storage.
