### ISSUE TITLE
Liste de course avec Quantité 

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#243]
Gérer l'ajout à la liste avec les quantités dans les recettes

**Comment by guillaumecauchois** [comment]
- [ ] Stocker des quantité pour chaque ingrédient ajouté dans les listes de recette
- [ ] Gestion des conversion & merge (Pour simplifier on affichera en gramme grace à l'equivalency stocké dans l'ingrédient directement pour faire les additions)

**Comment by guillaumecauchois** [comment]
Essayer de faire pour le 27/05
