### ISSUE TITLE
Meal Plan | Maquette pour RDV

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#244]
- [ ] Maquette du planning de repas
- [ ] Intégration maquette et des fonctionnalités (uniquement du front) dans le site (tout en dur)
- [ ] Petit blur ou truc sexy avec un message annonçant que la fonctionnalité arrive bientôt : "Bientôt, vous n'aurez plus à répondre à la question "Papa, maman, qu'est-ce qu'on mange ce soir ?" Recipy déterminera un planning de repas personnalisé !"
On intégrera réellement tout ça au prochain sprint ;)

**Comment by Thornolf** [comment]
![Web 1920 – 1](https://user-images.githubusercontent.com/15102389/58803573-216e8280-8610-11e9-89a2-6a88817c52e9.png)
