### ISSUE TITLE
Notebook | Refaire la view d'ajout d'une recette 

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#245]
Il faudrait faire l'ajout des recettes un peu similaire à celle que @LeBIGest  à fait pour les ingrédients sur les recettes

**Comment by guillaumecauchois** [comment]
@Thornolf on en est où dans la résolution de cela ?

**Comment by Thornolf** [comment]
Pas eu le temps de bosser là dessus avec le reste. J'y reviens dès que j'ai une issue qui se libère.
