### ISSUE TITLE
Alert system | Improvement

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#248]
Le système de notification pour dire qu'une action a fonctionner et niquel je trouve.
Cependant, est-il possible de faire en sorte que :
- [x] Augmenter légèrement la taille et/ou couleurs de l'alerte que ça soit plus visible

**Comment by Thornolf** [comment]
C'est quand les moments où tu retournes sur le site vitrine ? Ca c'est je penses les paths qu'on étaient mit en dure ou un soucis dans le routes.rb

**Comment by guillaumecauchois** [comment]
Yes probablement, j'ai eu l'exemple quand tu t'inscris sur le site, tu es redirigé vers la landing page avec la petite alert box pour te dire que ton inscription est prise en compte et qu'il faut consulter ses mails.
Le top serait qu'il nous renvoit vers la page d'accueil de Recipy (pas landing mais vraiment plateforme) avec le même message de la même manière.

**Comment by guillaumecauchois** [comment]
Suppression de la tâche de correction de redirection post submit

**Comment by guillaumecauchois** [comment]
J'ai discuté avec Julien, sont code pour les redirection avait été fait mais une erreur est apparue pendant le merge.
Peux-tu s'il te plait @Ventinc te charger de cet aspect finalement ?
- [ ] Ne plus rediriger vers la landing page au submit d'un form
