### ISSUE TITLE
Deployment | Auto link review app to the mailtrap

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#249]
Ce serait possible de linker directement le mailtrap à chaque fois qu'un environnement de PR est créé. A chaque fois que je fais une review je ne peux pas tester la plateforme car je n'ai pas de compte sur l'environnement (vierge) et je ne peux pas m'en créer un cause de ce soucis.

**Comment by Thornolf** [comment]
On a regardé avec Robin, le problème c'est que les tokens sous tout le temps différent... :(

**Comment by guillaumecauchois** [comment]
Je me dis qu'au moment du déploiement Heroku arrive bien à link la db alors pourquoi pas le mailtrap
A creuser...https://devcenter.heroku.com/articles/mailtrap#local-setup

**Comment by Thornolf** [comment]
Vincent l'a fait sauf pour certaines vars qu'on ne peut pas faire.
