### ISSUE TITLE
Readme vide

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#252]
On aurait pas un texte dans le site vitrine pour le mettre en ReadMe avec quelques images et un tutoriel pour lancer l'app ?

**Comment by guillaumecauchois** [comment]
Oui, ça pourrait être bien de le faire ;)
Il ne faut pas que ça prenne trop de temps mais oui !

**Comment by guillaumecauchois** [comment]
Sera à faire dans le prochain document DA2
