### ISSUE TITLE
Forms | Redirect to correct route

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#256]
Quand on valide un formulaire on est parfois redirigé vers la landing page...
A vérifier sur tous les formulaires et corriger

**Comment by guillaumecauchois** [comment]
On en est où dans cette issue, terminé ?

**Comment by LeBIGest** [comment]
- [ ] Après le changement de mot de passe

Crash si le mail n'est pas confirmé et non trouvé

**Comment by guillaumecauchois** [comment]
@LeBIGest peeux-tu me mettre à jour l'avancement de ce ticket, je ne sais pas où ça en est.

**Comment by guillaumecauchois** [comment]
Testé aujourd'hui, KO
Après avoir cliqué sur le lien de changement de mot de passe reçu par mail et après avoir saisi les nouvelles informations je suis renvoyé vers la landing page.
