### ISSUE TITLE
User | Edition du profil retourne une erreur

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#263]
J'ai essayer d'ajouter une photo de profil à mon compte utilisateur et le serveur me retourne une erreur, je ne comprends non-explicite. (Erreur en anglais d'ailleurs)

**Comment by MoonPandragon** [comment]
ça a jamais été fait l'upload de photo sur le profil utilisateur

**Comment by LeBIGest** [comment]
Si je l'avais fait quand guillaume voulait mettre un photo de profil sur son app
mais uniquement sur web pas mobile

**Comment by LeBIGest** [comment]
mais vu Faut tej le truc en haut 
mais en gros quand tu changes ta photo faut remettre ton mdp

**Comment by guillaumecauchois** [comment]
Non recetté
