### ISSUE TITLE
User | Suppression d'un compte utilisateur erreur

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#264]
- [x] Lorsque je demande la suppression de mon compte utilisateur sur la page de mon profil, il y'a du code HTML dans l'alerte javascript. Il faut corriger ça.
- [x] Le message à l'intérieur est en anglais, il faut prévoir une traduction.

**Comment by guillaumecauchois** [comment]
![image](https://user-images.githubusercontent.com/15093128/59180432-3e9dd680-8b65-11e9-8d4c-ebc8d261cd8e.png)

**Comment by Ventinc** [comment]
Resolve
