### ISSUE TITLE
Producer | Ne pas proposer la conversion du compte dés la création

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#265]
Je viens de me créer un compte sur le stagging. Dés que mon e-mail a été validé j'ai été redirigé vers cette page, mais il ne faut pas !

**Comment by guillaumecauchois** [comment]
![image](https://user-images.githubusercontent.com/15093128/59182516-43b15480-8b6a-11e9-8a38-4e291f91b1cd.png)

**Comment by MoonPandragon** [comment]
Sur la staging? J'ai pas ça perso ca me renvoie a /

**Comment by guillaumecauchois** [comment]
D'accord peut-être une fausse manipulation il faut que je recheck.

**Comment by MoonPandragon** [comment]
C'est fix avec la PR fix/redir 
je close
