### ISSUE TITLE
Changer le mail des mails envoyés par recipy (ex: confirmation d'inscription)

### ISSUE THREAD

**Issue by LeBIGest** [recipyhq/recipy#270]
Comme vu dans les tests avec la prod le mail de recipy est : "from@example.com" faut changer ça.

Fichiers sûrement concernés : _application_mailer.rb_ et _devise_mailer.rb_

**Comment by guillaumecauchois** [comment]
Bien vu Robin !
Nouvelle adresse à intégrer : noreply@recipy.fr
