### ISSUE TITLE
Cooker | Intégration du nutriscore

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#272]
Je sais pas si vous avez remarqué les dernières déclarations de notre cher gouvernement mais ils vont rendre le nutriscore probablement obligatoire sur toutes les denrés alimentaires. L'intégré sur le site pourrait être intéressant je trouves. Qu'en pensez-vous ?

source: http://www.mangerbouger.fr/Manger-Mieux/Comment-manger-mieux/Comprendre-les-infos-nutritionnelles2/Le-Nutri-Score-l-information-nutritionnelle-en-un-coup-d-oeil

**Comment by guillaumecauchois** [comment]
Le problème c'est que cela ne s'applique qu'aux produits préparés et non pas au ingrédients directement.
Par contre on peut certainement faire en sorte d'ajouter notre propre nutriscore (un peu à la Yuka) pour donner une indication clair sur la qualité nutritionnelle des ingrédients à intégrés à une recette et voir même grâce à l'intégration de ces ingrédients dans une recette de pouvoir générer un nutriscore pour la recette elle-même. Qu'en penses-tu ? Et les autres ?

**Comment by Thornolf** [comment]
Ouais on pourrait faire ça, un genre de formule qui calculerer le nutriscore en fonction des ingrédients me semble intéressant.

**Comment by guillaumecauchois** [comment]
Nécessite la réalisation du ticket #276

**Comment by guillaumecauchois** [comment]
Doublon #276
