### ISSUE TITLE
Cooker | Intégration de la nutrition au sein des ingrédients

### ISSUE THREAD

**Issue by guillobits** [recipyhq/recipy#276]
- [ ] Intégration des données nutritionnelles des ingrédients
- [ ] Affichage des informations sur la page d'une recette (cumul calculer grâces aux
ingrédients)
- [ ] Implémenter cette notion pour le planning de repas (gestion des régimes spécifiques)
- [ ] Dans le but d'afficher rapidement et de manière ludique la qualité nutritionnelle d'un ingrédient nous allons intégrer un 'recipy-score" sur la qualité des ingrédients

**Comment by PierreCooper** [comment]
On en a déjà débattu mais je ne pense pas que cette issue, ainsi son doublon nutriscore, soient pertinentes. L'indication des calories et macro-nutriments ne fait, selon moi, pas parti des objectifs de Recipy

**Comment by guillaumecauchois** [comment]
T'as raison c'est pour ça qu'il est dans le milestone "long-term" c'est a dire que c'est un truc qu'on ne fera pas dans le cadre de l'eip mais des potentiels amélioration qu'on pourrait vendre en présentation
