### ISSUE TITLE
Meal plan | Maquette visuelle 

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#278]
- [ ] Création d'une maquette faisant apparaitre l'ensemble des fonctionnalités liées au planning de repas

**Comment by Thornolf** [comment]
Je sais pas trop où le noter donc je le met là :
J'ai lu dans un bouquin e cuisine qui bosser sur des plannings, qu'ils avaient l'astuce de capé le temps de prépa global de toutes les recettes de la semaine à un temps maximum. Genre les repas de toute la semaine ne pourront pas dépasser une préparation de 3h en tout etc. Je trouve le principe intéressant.

**Comment by Thornolf** [comment]
Je relink la maquette ici parce qu'elle était dans #244 

![image](https://user-images.githubusercontent.com/15102389/60664001-1605b580-9e61-11e9-9a58-6e4421cf91f0.png)

**Comment by guillaumecauchois** [comment]
Ok pour la maquette.
@Ventinc a intégrer / faire évoluer...
