### ISSUE TITLE
BETA | Installation du serveur de production

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#286]
Je ne sais pas où tu en été dans l'installation du serveur de BETA @LeBIGest 
Est-ce que tu peux me faire un commentaire avec les choses manquantes pour la mise en route du serveur de production ?
Je rajoute : 
- [ ] Mise en place du nom de domaine (voir difficulté de liaison avec Heroku et son load balancing...)

**Comment by LeBIGest** [comment]
[ ] le nom des mails envoyés par recipy

**Comment by guillaumecauchois** [comment]
Ok merci Robin. Je ferme le ticket et j'en refait un pour set le nom de domaine.
