### ISSUE TITLE
E² | Les documents à rendre

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#289]
- [x]  Logo définitif - pour le 18/08/2019 23h42 au plus tard
- [x] Description pour le Book EIP - pour le 18/08/2019 23h42 au plus tard
- [ ] Affiche A1 - pour le 29/09/2019 23h42 au plus tard
- [ ] Flyer A5 - pour le 29/09/2019 23h42 au plus tard

**Comment by guillaumecauchois** [comment]
Affiche et flyer par Pierre
Reste par Guillaume

**Comment by LeBIGest** [comment]
Pour le 18/08/2019 : Rendre le DA1 (Document retour utilisateurs)
https://labeip.epitech.eu/svn/eip/public/2020/2020_DA1_Consignes.pdf

**Comment by guillaumecauchois** [comment]
DA1 OK
LOGO OK
BOOK EIP OK

**Comment by Thornolf** [comment]
@PierreCooper tu en es où pour les docs graphiques ?

**Comment by guillaumecauchois** [comment]
Ok done
