### ISSUE TITLE
Devise | OAuth | Google

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#29]
Avec Devise, nous pouvons simplement setup une authentification OAuth.

- [x] Créer une application Google
- [x] Configurer l'initializer OAuth
- [x] Ajouter le button sur la page de `sign_in`
- [x] Ajouter le button sur la page de `sign_up`

**Comment by Panzershrekk** [comment]
Les pages "sign_in" et "sign_up" sont crées de base ?

**Comment by beauraF** [comment]
C'est des vues créé par Devise elles sont déjà présente sur le projet. Il y a une story pour les personnaliser.
