### ISSUE TITLE
Cooker | Liste de courses | Définir un quantité dans l'ajout

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#299]
Sauf erreur de ma part, je ne trouve pas de moyen de séléctionner une quantité pour les ingrédients que l'on ajoute soit même à une liste. Il faudrait faire en sorte que cela soit possible de cette manière :

Sélectionner un ingrédient | Séléctionner une quantité | (Séléction entre grammes, kilos, pincés ...)

![image](https://user-images.githubusercontent.com/15093128/62824957-75fc2400-bba4-11e9-9465-4d216812c5a7.png)

**Comment by PierreCooper** [comment]
Comment faire si la quantité de l'ingrédient dans la liste est différent de celle dans la recette ? Est ce qu'on merge les deux quantités (un milliard d'équivalences à gérer) ou alors on affiche les deux ?

**Comment by Panzershrekk** [comment]
Céline à déjà dis ce qu'il fallait faire, on duplique l'ingrédient

**Comment by Thornolf** [comment]
Après techniquement tu as soit des grammes soit des litres grossièrement, si t'as une tranche en soit la tranche devrait avoir une équivalence en gramme, un verre devrait avoir une equivalence en litre ou centilitre. 
Pour l'instant on préférera la solution proposer directement par Céline qu'est en effet plus simple à appliquer mais je penses que plus tard faudrait juste rajouter quelques méthodes pour faire les équivalences rapidement et simplement.

**Comment by PierreCooper** [comment]
On rattrape sur l'issue #340
