### ISSUE TITLE
Cooker | Erreur sur la création d'une recette vide le formulaire

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#303]
Lorsqu'une erreur intervient dans le processus de création d'une recette, tout le formulaire est vidé entièrement. Dommage quand on vient de créer sa recette et que l'on a tout perdu...
- [ ] A corriger

**Comment by LeBIGest** [comment]
Je suis au courant mais je sais pas comment le régler j'ai essayé mais je sais pas comment le régler

**Comment by guillaumecauchois** [comment]
Doublon
