### ISSUE TITLE
Recette aléatoire | Bug quand recette supprimée

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#308]
J'ai eu une erreur en voulant accéder à une recette aléatoire grâce au lieu sur la page d'accueil.
La recette n'existaient pas.
Je soupçonne que lorsqu'on supprime la recette 21 par exemple alors que l'id max est 35 par exemple on a une chance de tomber sur 21 alors qu'elle est supprimée.

**Comment by Thornolf** [comment]
J'ai vérifié en local, et je n'arrives pas à reproduire le bug. J'ai vérifié la méthode de random qui est en accord avec ce qu'il faut faire : `@random_recipe = Recipe.order("RANDOM()").first`

Après avoir supprimé petit à petit les recettes tout en faisant des F5 etc. je n'ai jamais eu le bug. Et une fois que le site n'a plus de recette, aucun problème quand même.

Faudrait voir pour le reproduire sur le staging.

**Comment by guillaumecauchois** [comment]
OK, bon on cherche pas, ça ne m'est arrivé qu'une seule fois. J'ai jamais eu le problème depuis.
On close. Merci @Thornolf
