### ISSUE TITLE
Recipe - Erreur création d'une recette quand image invalide

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#317]
External error quand upload d'un fichier quelconque au lieu d'une image

**Comment by Thornolf** [comment]
@LeBIGest est dessus si j'ai bien compris, il a déjà fix des trucs d'un autre côté

**Comment by guillaumecauchois** [comment]
@LeBIGest tu confirmes que c'est fix ?

**Comment by Thornolf** [comment]
C'est fix.
