### ISSUE TITLE
Redirection des mails sur Recipy.fr au lieu du contenaire en PR

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#325]
Quand on créer un compte sur une PR, et qu'on veut le confirmer, le lien de confirmation redirige vers Recipy.fr et pas le container en question.

Le workaround qu'on a trouvé pour l'instant : 

* Clic droit sur confirmatin et récupéré le lien
* Remplacer recipy.fr par l'adresse de la PR

Je penses que ça vient d'une de tes modifications @Ventinc, est-ce que tu saurais comment le fix ?

**Comment by guillaumecauchois** [comment]
Nous n'avons toujours pas trouvé de solution à ce problème mais dans le cadre de notre EIP nous ne nous attarderons pas sur ce problème. Tant pis...

**Comment by Thornolf** [comment]
@guillobits Any news on this ?
