### ISSUE TITLE
Recipe | Pouvoir ajouter une vidéo depuis Youtube

### ISSUE THREAD

**Issue by guillobits** [recipyhq/recipy#327]
Il pourrait être très intéressant de proposer au cuisinier de voir des recettes sous forme de vidéo (format au choix de l'auteur de la recette), mais de notre côté essayer de mettre en place des recette en format court rapide qu'on pourra partager sur les réseaux sociaux (15 secondes maximum).

De manière technique juste permettre d'ajouter un lieu youtube vers une vidéo et un lien cliquable à côté du champs pour rediriger vers l'uplaoder de vidéo de Youtube.

**Comment by Thornolf** [comment]
Est-ce bien pertinent à ce stade ?

**Comment by guillaumecauchois** [comment]
Bah je pense que c'est un plus avoir de quoi partager sur les réseaux sociaux, les utilisateurs de Facebook par exemple sont très friands de contenus rapides de cuisine. Ils ajoutent à leurs favoris tout ça et ça créé de l'engagement.
Après en terme de ressource humaine ça prends littéralement un heure de travail d'implémenter ça, c'est pas très chronophage.
