### ISSUE TITLE
Layout | Navbar

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#33]
Afin d'avoir un début de squelette, il faut mettre en place la navbar `desktop` et `mobile` (comprendre responsive) qu'on va intégrer au `layout`.

**Comment by Thornolf** [comment]
La navbar est sur un côté ou en haut ?

**Comment by beauraF** [comment]
On va en placer une en haut et la déplacer sur le coté avec un `toggle` sur une vue plus mobile

**Comment by guillaumecauchois** [comment]
Je valide le ticket pour la navbar qui a été corrigé plusieurs fois. Recréer une issue en cas de besoin.
