### ISSUE TITLE
Desactivation de la validation des ingrédients

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#332]
On a pas assez d'ingrédient pour l'instant et ça casse vraiment la création de recette chez les nouveaux utilisateurs. J'ai déjà eu le cas avec un user qui voulait faire une recette qui utiliser un nouvelle ingrédient pas encore présent dans la DB.
Faudrait désactiver cette limitation et ajouter automatiquement en DB l'ingrédient lors de la validation de la recette ça sera beaucoup plus simple ne serais-ce qu'au début, parce que je sens que lors des WarmUp Days on va avoir des soucis quand des gens vont tester le produit.

**Comment by guillaumecauchois** [comment]
Ouais plutôt d'accord, j'y pensais aussi...

**Comment by Thornolf** [comment]
Quitte à autoriser n recettes par personnes par jour par exemple si quelqu'un veut troll et nous flood la DB.

**Comment by Thornolf** [comment]
On peut proposer un ingrédient directement maintenant mais le fix est tempo, faut quand même proposer.
