### ISSUE TITLE
Layout | Footer

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#34]
Afin d'avoir un début de squelette, il faut mettre en place le footer qu'on va intégrer au `layout`.
Ne pas sous estimer le footer, c'est un point d'entrée essentiel pour les crawler et donc le SEO.

**Comment by beauraF** [comment]
Je te fais une réponse "complète" soon !

**Comment by beauraF** [comment]
Ok, la partie importante du footer c'est de permettre au crawler de crawler toutes les pages importante du site. Le crawler clique sur tout les liens, dès qu'il n'arrive plus à accéder à une page non visité il quitte le site.

C'est pourquoi avoir une "map" du site dans le footer est essentiel. Ce n'est pas toujours ce qu'il y a de plus sexy, mais c'est super important.

Le footer de docto est un bon exemple : 

![capture d ecran 2018-07-11 a 15 41 33](https://user-images.githubusercontent.com/12185788/42575580-2d6ccce0-8521-11e8-95e6-70b04796dc37.png)

**Comment by Thornolf** [comment]
https://www.orbitmedia.com/blog/website-footer-design-best-practices/
