### ISSUE TITLE
Amélioration des listes de courses

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#345]
Trier le retour API par rayon

**Comment by PierreCooper** [comment]
@guillaumecauchois peux-tu me donner + de précisions sur ce que tu attends ?

**Comment by guillaumecauchois** [comment]
En gros si possible, c'est pour améliorer l'affichage sur mobile (vu par rapport au retours fait par Céline et le mec de l'UI) : 
Il faudrait que l'api de la liste de course retourne la liste groupée par rayons genre
Rayons fruit et légume contient ça ça ça
Rayon truc contient ça ça ça.

@Panzershrekk il faudra modifier le code en conséquence.
