### ISSUE TITLE
Training | Thomas

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#35]
Voici `un peu` de lecture pour débuter sur de bonne base. Le but n'est pas de vous faire apprendre la doc de rails par coeur, mais surtout que vous ayez conscience que cela existe afin d'avoir un début de réponse sur vos questions et ou guider vos recherches.

Courage ! 🔥

- Ruby
  - [x] [Variables](https://www.grafikart.fr/formations/apprendre-ruby/variables)
  - [x] [Conditions](https://www.grafikart.fr/formations/apprendre-ruby/conditions)
  - [x] [Array & Hash](https://www.grafikart.fr/formations/apprendre-ruby/array-hash)
  - [x] [Loops](https://www.grafikart.fr/formations/apprendre-ruby/loops)
  - [x] [Methods](https://www.grafikart.fr/formations/apprendre-ruby/method)
  - [x] [Typage](https://www.grafikart.fr/formations/apprendre-ruby/typage)
  - [x] [Proc & Block](https://www.grafikart.fr/formations/apprendre-ruby/block-proc-lambda)
  - [x] [Class](https://www.grafikart.fr/formations/apprendre-ruby/poo-objet)
  - [x] [Heritage](https://www.grafikart.fr/formations/apprendre-ruby/poo-heritage)
  - [x] [Namespace](https://www.grafikart.fr/formations/apprendre-ruby/poo-modules-namespaces)
  - [x] [Mixins](https://www.grafikart.fr/formations/apprendre-ruby/poo-modules-mixins)
  - [x] [Exceptions](https://www.grafikart.fr/formations/apprendre-ruby/exceptions)
- Rails :
  - [x] [Getting Started](http://guides.rubyonrails.org/getting_started.html)
  - [x] Model | [ActiveRecord Basics](http://guides.rubyonrails.org/active_record_basics.html)
  - [x] Model | [ActiveRecord Migrations](http://guides.rubyonrails.org/active_record_migrations.html)
  - [x] Model | [ActiveRecord Validations](http://guides.rubyonrails.org/active_record_validations.html)
  - [x] Model | [ActiveRecord Callbacks](http://guides.rubyonrails.org/active_record_callbacks.html)
  - [x] Model | [ActiveRecord Associations](http://guides.rubyonrails.org/association_basics.html)
  - [x] Model | [ActiveRecord Query Interface](http://guides.rubyonrails.org/active_record_querying.html)
  - [x] Model | [ActiveModel Basics](http://guides.rubyonrails.org/active_model_basics.html)
  - [x] Views | [ActionView Overview](http://guides.rubyonrails.org/action_view_overview.html)
  - [x] Views | [Layout & Rendering](http://guides.rubyonrails.org/layouts_and_rendering.html)
  - [x] Views | [ActionView Form Helper](http://guides.rubyonrails.org/form_helpers.html)
  - [x] Controllers | [ActionController Overview](http://guides.rubyonrails.org/action_controller_overview.html)
  - [x] Controllers | [ActionController Routing](http://guides.rubyonrails.org/routing.html)
  - [x] [Rails i18n](http://guides.rubyonrails.org/i18n.html)
  - [x] [ActionMailer Basics](http://guides.rubyonrails.org/action_mailer_basics.html)
  - [x] [ActiveJob Basics](http://guides.rubyonrails.org/active_job_basics.html)
  - [x] [ActiveStorage Overview](http://guides.rubyonrails.org/active_storage_overview.html)
  - [x] [Rails Command Line](http://guides.rubyonrails.org/command_line.html)
  - [x] [Debugging Rails Application](http://guides.rubyonrails.org/debugging_rails_applications.html)
  - [x] [The Assets Pipeline](http://guides.rubyonrails.org/asset_pipeline.html)
  - [x] [Working with JS](http://guides.rubyonrails.org/working_with_javascript_in_rails.html)
  - [x] [ActionCable Overview](http://guides.rubyonrails.org/action_cable_overview.html)
  - [x] Grafikart | [Installation](https://www.grafikart.fr/formations/ruby-on-rails/installation)
  - [x] Grafikart | [Notre première page](https://www.grafikart.fr/formations/ruby-on-rails/premiers-pas)
  - [x] Grafikart | [Migrations](https://www.grafikart.fr/formations/ruby-on-rails/migrations)
  - [x] Grafikart | [Models](https://www.grafikart.fr/formations/ruby-on-rails/models)
  - [x] Grafikart | [CRUD](https://www.grafikart.fr/formations/ruby-on-rails/crud)
  - [x] Grafikart | Controllers | [Filters](https://www.grafikart.fr/formations/ruby-on-rails/controllers-filers)
  - [x] Grafikart | Controllers | [Sessions & Cookies](https://www.grafikart.fr/formations/ruby-on-rails/sessions-cookies)
  - [x] Grafikart | Controllers | [Gérer plusieurs format](https://www.grafikart.fr/formations/ruby-on-rails/controllers-formats)
  - [x] Grafikart | Models | [Validations](https://www.grafikart.fr/formations/ruby-on-rails/models-validations)
  - [x] Grafikart | Models | [Callbacks](https://www.grafikart.fr/formations/ruby-on-rails/models-callbacks)
  - [x] Grafikart | Models | [Scopes](https://www.grafikart.fr/formations/ruby-on-rails/models-scopes)
  - [x] Grafikart | Models | [Associations](https://www.grafikart.fr/formations/ruby-on-rails/models-associations)
  - [x] Grafikart | Views | [Partials & Layout](https://www.grafikart.fr/formations/ruby-on-rails/partials-layout)
  - [x] Grafikart | Views | [Helpers](https://www.grafikart.fr/formations/ruby-on-rails/helpers)
  - [x] Grafikart | [Assets Pipeline](https://www.grafikart.fr/formations/ruby-on-rails/asset-pipeline)
  - [x] Grafikart | [ActionMailer](https://www.grafikart.fr/formations/ruby-on-rails/actionmailer)
- Rails Test :
  - [ ] [Testing Rails Application](http://guides.rubyonrails.org/testing.html)
  - [ ] RSpec | [Documentation](http://rspec.info/documentation/3.7/rspec-rails/)
  - [ ] Capybara | [The DSL](https://www.rubydoc.info/github/teamcapybara/capybara/master#The_DSL)
  - [ ] FactoryBot | [Documentation](https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md#Defining_factories)
  - [ ] ShouldaMatchers | [Documentation](http://matchers.shoulda.io/docs/v3.1.1/)
  - [ ] FFaker | [Documentation](https://github.com/ffaker/ffaker)
  - [ ] Grafikart | [RSpec](https://www.grafikart.fr/formations/ruby-on-rails/rspec-unit-test)
- Important Gems
  - [ ] [Turbolinks](https://github.com/turbolinks/turbolinks)
  - [ ] [JBuilder](https://github.com/rails/jbuilder)
  - [ ] [Figaro](https://github.com/laserlemon/figaro)
  - [ ] [Pundit](https://github.com/varvet/pundit)
  - [ ] [Devise](https://github.com/plataformatec/devise#controller-filters-and-helpers)
  - [ ] [Devise Auth Token](https://devise-token-auth.gitbook.io/devise-token-auth/usage)
  - [ ] Grafikart | [Devise](https://www.grafikart.fr/formations/ruby-on-rails/devise-omniauth)
  - [ ] [ActiveAdmin](https://activeadmin.info/2-resource-customization.html)
  - [ ] [StrongMigration](https://github.com/ankane/strong_migrations#the-zero-downtime-way)
  - [ ] [SimpleForm](https://github.com/plataformatec/simple_form#usage)
  - [ ] Grafikart | [SimpleForm](https://www.grafikart.fr/formations/ruby-on-rails/simple-form)
- Stimulus :
  - [ ] [Origin](https://stimulusjs.org/handbook/origin)
  - [ ] [Introduction](https://stimulusjs.org/handbook/introduction)
  - [ ] [Hello, Stimulus](https://stimulusjs.org/handbook/hello-stimulus)
  - [ ] [Building Something Real](https://stimulusjs.org/handbook/building-something-real)
  - [ ] [Managing State](https://stimulusjs.org/handbook/managing-state)
  - [ ] [Working with external resources](https://stimulusjs.org/handbook/working-with-external-resources)
- Style
  - [ ] [Sass](https://sass-lang.com/guide)
  - [ ] [OOCSS](https://www.smashingmagazine.com/2011/12/an-introduction-to-object-oriented-css-oocss/)
  - [ ] [BEM](https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/)
  - [ ] [UIKit](https://getuikit.com/docs/introduction)

**Comment by Panzershrekk** [comment]
@beauraF On peut commencer à faire nos issues où il reste des trucs à setup ? Si oui on créé une branche à partir de master?
Dernière question tu conseil quoi comme IDE pour faire du Rails ? (Rubymine je suppose)

**Comment by beauraF** [comment]
@Panzershrekk oui tu peux commencer. Le projet est globalement setup. Encore un petit truc sur `heroku` et mettre la `CI`.

Oui, tu tires une nouvelle branche depuis master. Après libre à vous de faire des "sous-branche" si vous êtes à plusieurs sur une même feature. Dans ce cas tu tires une fois de master, puis toi et l'autre personne tiré une nouvelle branche depuis la nouvelle branche. Je sais pas si c'est clair.
Dans tous les cas cela doit resté rare et marginal.

RubyMine, après les IDE mainstream aka Atom, VSCode font largement le taff.
