### ISSUE TITLE
RGPD | Modification des textes et ajouts des clauses manquantes sur les formulaires

### ISSUE THREAD

**Issue by guillobits** [recipyhq/recipy#373]
- [ ] Ajouter une clause de récupération de données personnels sur tous les formulaires de la plateforme récupérant des données personnelles.
- [ ] Ajouter dans les mentions légales une clause de non-responsabilité par rapport à l'affichage des allergènes d'une recette.

**Comment by Thornolf** [comment]
C'est finit ça @guillaumecauchois ?
