### ISSUE TITLE
Faire une redir pour Celine

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#376]
Faire une redir pour ce qu'à demander Céline. @guillaumecauchois  en sait plus.

**Comment by guillaumecauchois** [comment]
Il faut éditer une requête HTTP 301 Redirect vers recipy.fr ;)

**Comment by guillaumecauchois** [comment]
J'ai commencé un truc c'est pas parfait, mais ça arrive
En fait c'est juste qu'il redirige auto vers recipy.fr/2020/recipy ...

**Comment by Thornolf** [comment]
T'en es où là dedans ?

**Comment by Thornolf** [comment]
C'est fait. Je close.
