### ISSUE TITLE
Delivery | Mise en places des scénarios

### ISSUE THREAD

**Issue by guillaumecauchois** [recipyhq/recipy#379]
- [ ] Répertorier les scénarios dans une timeline précise avec un démonstrateur assigné.

**Comment by Thornolf** [comment]
Je partages les scénarios ici : https://docs.google.com/document/d/1NVUyw5R0Bv7cL3GRBWND-qcyIorjLb5Pkp-85bY36i0/edit

**Comment by Thornolf** [comment]
Il faudrait faire un tableau ou autre avec toutes les features du site histoire de ne rien oublier.

**Comment by Thornolf** [comment]
Le excel : https://docs.google.com/spreadsheets/d/1P3ZTIco2DJsq0ZMtjv9O-x4B0_WqDvG1ZciEFxKMdk8/edit#gid=0

**Comment by Thornolf** [comment]
Tout est fait c'est nickel, plus qu'à close après le Delivery.
