### ISSUE TITLE
Multiples fixes sur le front

### ISSUE THREAD

**Issue by Thornolf** [recipyhq/recipy#398]
- [x]  Fonction recherche dans le menu burger pas très visible, la déplacé dans la navbar

- [x] Modification du href dans le menu burger

- [x] Error quand on édite une recette

- [x]  Ajout de la fonction edit juste à côté du titre de la recette 

- [x]  Edition d'un notebook retourn erreur de trad :fr.notebook.edit.valid

- [x]  Modifier le texte description du profil

- [x]  Le bouton producteur ne fonctionne pas, il renvoie sur aucune page.

![image](https://user-images.githubusercontent.com/15102389/69893264-5a618880-130f-11ea-8baf-244ef828fa86.png)

**Comment by Arthaox** [comment]
- ajouter un bouton "retour au profil producteur" dans la page d'edit de produit
- changer le texte de la notification de création du compte producteur
- inverser les inputs "tag" et "point de vente" dans la page création d'un produit
