### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by almereyda** [recipyhq/recipy#418]
When clicking the website link http://recipy.fr/, I am reported that the site cannot be reached.

Tested with http://isup.me/http://recipy.fr/

**Comment by Thornolf** [comment]
Hey, 

Thank you for reporting the issue. It's a student projet so we are not paying the domain anymore but you can access it via : https://production-recipy.herokuapp.com/ 😃 

We are going to make the necessary changes to edit it. By the way how did you find us ? 🤔 

Have a nice day 😄

**Comment by almereyda** [comment]
Thanks for changing the link of the GitHub project. This can be closed then.

For you are asking, I have found you in searching through https://github.com/topics/cooking
