### ISSUE TITLE
User | user#edit

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#45]
Sur ce sprint nous allons également construire la page `user#edit`. Cette page est importante à construire dans les première car nous allons avoir besoins de l'update régulièrement.

Objectif : permettre à un utilisateur de pouvoir update ses informations perso

**Comment by Arthaox** [comment]
Quelle est la différence entre registration/edit et user#edit ? Les deux correspondent aux informations ajouté durant l'inscription non ?

**Comment by beauraF** [comment]
Oui et non. Car beaucoup de `settings` vont se rajouté. Mais sur le principe ce sont effectivement des routes qui se chevauchent. On va surement désactiver la route devise. J'y réfléchis et j'adapterai les story.
