### ISSUE TITLE
Devise | View | confirmations/new

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#46]
Devise met à disposition un generator afin de générer les vues pour pouvoir les override.
Dans cette story nous allons personnaliser la view `confirmations/new`.

**Comment by Panzershrekk** [comment]
Que fait new ? Où et cmment on override les vues ?

**Comment by beauraF** [comment]
`new` est l'une des actions `CRUD`. Dans la plus part des cas, c'est une page avec formulaire où tu vas pouvoir créer une `resource`. Tu fais un `GET` sur `/new` pour afficher la page de création puis ton formulaire fait un `POST` sur `/create`.

Dans ton cas présent, c'est un peu particulier. A confirmer mais je pense que c'est la page qui "confirme la confirmation de ton compte".

Pour ce qui est de l'override : dans cette story #28 on va générer toute les vues `Devise`. Il suffira ensuite de changer le code de la page directement dedans.

**Comment by Panzershrekk** [comment]
D'accord elle sont pas encore générées du coup ?

**Comment by beauraF** [comment]
Non pas encore. Il faut faire #28 d'abord 😉
