### ISSUE TITLE
Devise | View |  unlocks/new

### ISSUE THREAD

**Issue by beauraF** [recipyhq/recipy#58]
Devise met à disposition un generator afin de générer les vues pour pouvoir les override.
Dans cette story nous allons personnaliser la view ` unlocks/new`.

**Comment by Thornolf** [comment]
Tu peux développer un peu plus sur ce que c'est unlocks ?

**Comment by beauraF** [comment]
Si tu te trompes de mot de passe 20 fois, ton compte est lock. Tu reçois un email t'invitant à unlock ton account avec un lien pointant vers `unlocks/new`.
