### ISSUE TITLE
UI | Choix couleurs

### ISSUE THREAD

**Issue by LeBIGest** [recipyhq/recipy#70]
Issue pour déterminer le thème pour le front du site Web.

**Inspirations  :** 📌
- https://www.airbnb.fr/
- https://nomadlist.com/
- http://collectui.com/
- https://www.ubereats.com/fr-FR/stores/

**Couleurs  :** 🎨
- https://flatuicolors.com/  (Liste de palettes)

**Emotes  :** 👀
- https://twemoji.twitter.com/

**Features  :** ⚙️
- https://dribbble.com/shots/

**Comment by LeBIGest** [comment]
site pour les palettes de couleurs : https://flatuicolors.com/

**Comment by LeBIGest** [comment]
Une première version :
https://color.adobe.com/Recipy-theme-color-theme-11171881/

**Comment by Thornolf** [comment]
De gauche à droite : 
#FF9A3B
#FBFBFB
#3C3C3C
#424242
#474747

**Comment by Thornolf** [comment]
Il faudra qu'on modifie les css via ça je penses : https://getuikit.com/v2/docs/customizer.html une fois qu'on sera totalement décidé

**Comment by guillaumecauchois** [comment]
Les couleurs semblent convenir pour tout le monde.
